version: "3"
services:
  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - ./mongo-data:/data/db
  custodian:
    build: ./
    container_name: custodian
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      - CUSTODIAN_MONGO_DB_URI=mongodb://mongo:27017/custodian
