openapi: '3.0.2'
info:
  title: Custodian
  version: '0.0.0'
paths:
  /files:
    get:
      summary: Get all files
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "file.yaml#/files"
    post:
      summary: Add a file
      description: >
        Add a file from multipart data and return its json representation
      requestBody:
        $ref: "file.yaml#/newFileRequestBody"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "file.yaml#/file"
  /files/{stringId}:
    get:
      summary: Get file by its string identifier
      parameters:
        - $ref: "file.yaml#/stringIdPath"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "file.yaml#/file"
